### ISSUE TITLE
Observations

### ISSUE THREAD

**Issue by satwik163** [gkrishnaks/Warn-Common-Password#1]
Hi,
Just found an observation that if i enter !!!!!!! as a password, I get a message that password is weak but when i enter &&&&&&  or ]]]]]] or }}}}} there is no message and it seems that the passwords are not weak.

**Comment by gkrishnaks** [comment]
Hi Satwik.
The add-on does not and is not intended to "measure" the strength of a password. It checks if the password is present in top 500000 common password list : https://github.com/gkrishnaks/Warn-Common-Password/blob/master/data.JSON

Thank you for your observation - in the next version, I will just add the "repeat same symbol 6 times as password" like the ones you tried into the "word list" manually.
